FHIR R4: {
  shape: rectangle
  label.near: top-left
  style.fill: "#e6edff"
  zibs 2020: {
    shape: rectangle
    label.near: top-left
    style.fill: "#c8d6f9"
    nl-core: {
      shape: rectangle
      label.near: top-left
      style.fill: "#84a1ec"
      IKNL NCR-EHR: {
        shape: rectangle
        style.fill: "#5679d5"
        style.font-color: "#ffffff"
      }
      Some Other Profile: {
        shape: rectangle
        style.fill: "#5679d5"
        style.font-color: "#ffffff"
      }
    }
  }
}