FHIR R4: {
    shape: oval
    label.near: outside-left-center
    zibs 2020: {
      shape: oval
      label.near: outside-left-center
      nl-core: {
        shape: oval
        label.near: outside-left-center
        IKNL NCR-EHR: {
          shape: oval
        }
        Some Other Profile: {
          shape: oval
        }
      }
    }
  }